### ISSUE TITLE
SAM Construction Panel

### ISSUE THREAD

**Issue by ProNuBs** [saesrpg/saesrpg-group#28]
I'd like to request a construction panel (mainly to enhance RP experiences)  for the following SAM spawns:

SAM Chief - (sam-hq)
SAM EMS Division - (sam-para)
SAM Air Division - (sam-air)
SAM Sea Division - (sam-sea)

Panel would have the following object ID's :

1461
1637
1640
5154
12990
10834
16502
17068
11145
10841
1612
5406
3578
3886
6188
6189
6300
9818
9819
9822
10227
10230
10793
14463
14537
18090
14831
9247
11431
18236
3615
1684
967
14780
14781
13666
13629
14791
3819
1776
1977
2219
2220
2215
2425
3399
5130
3279
3280
3386
3390
3391
3392
3393
3394
3395
3396
3397
3791
16644
1210
1212
1239
1240
1241
1318
1550
1575
1576
1577
1578
1579
1580
1650
1654
2036
2690
918
1217
1218
1222
1225
1244
1676
1686
1985
3374
3515
3525
3386
3743
6963
7392
8979
8980
11470
10397
1211
1216
1223
1226
1231
1232
1257
1238
1340
1341
1342
1346
1478
1570
1571
6299
3463
3861
3862
913
912
942
939
933
1227
1224
1339
1343
1558
16337
14558
18260
18257
931
944
1271
1431
1685
2041
2359
2476
2669
3365
3761
3796
3799
896
897
745
744
16115
16117
625
626
627
628
651
640
677
638
808
878
869
948
742
615
618
620
621
641
645
669
685
690
4726
2510
16341
7980
1634
1633
1632
1655
2714
1997 (hospital trolley 1, the modded stretcher)

**Comment by ProNuBs** [comment]
We would also like the trencher (it's a modded object though and we're not quite sure what object I'd it is, will update when I find out)

**Comment by ProNuBs** [comment]
> We would also like the trencher (it's a modded object though and we're not quite sure what object I'd it is, will update when I find out)

Added it to the list

**Comment by SAESKain** [comment]
1640
5154
12990
10834
16502
17068
11145
10841
1612
5406
6188
6189
6300
9818
9819
9822
10227
10230
10793
14463
14537
18090
14831
9247
11431
18236
3615
14780
13629
14791
1977
2219
2220
2215
2425
3399
3280
3390
3391
3392
3393
3394
3395
3396
3397
3791
1239
1240
1241
1318
1577
1578
1579
1580
1218
1222
1225
1244
1686
3374
3525
6963
7392
8979
8980
11470
10397
1226
1340
6299
3463
913
912
939
933
1227
1339
1343
16337
14558
18260
18257
1271
1431
2041
2476
3365
3799
896
897
745
16115
16117
677
808
878
869
948
742
615
618
620
621
641
645
685
690
4726
2510
16341
1633
1655
2714

All the above are not on any existing construction panels and therefore need short applicable names giving to them as you would see in the construction panel. Quite simply no ones paying me enough to do that myself so that's your job.

As it stands WITHOUT any of the above item ids, you have 64 items on the panel which already did have names.

**Comment by SAESKain** [comment]
https://pastebin.com/S2LfZSgv

**Comment by SScorpyo** [comment]
https://pastebin.com/tdQwf5SB
